export class Employe{
    constructor(
        public id?:number,
        public photoDeProfil?:string,
        public logoEntreprise?:string,
        public photoCouverture?:string,
        public titreEmploi?:string,
        public departement?:string,
        public nomEntreprise?:string,
        public numTelephone?:string,
        public urlEntreprise?:string,
        public adresse?:string,
        public couleur?:string,
        public police?:string,
        public fbLink?:string,
        public xLink?:string,
        public instagramLink?:string,
        public linkedinLink?:string,
        public youtubeLink?:string,
        public snapchatLink?:string,
        public tiktokLink?:string,
        public twitchLink?:string,
        public yelpLink?:string,
        public whatsappLink?:string,
        public signalLink?:string,
        public discordLink?:string,
        public skypeLink?:string,
        public telegramLink?:string,
        public githubLink?:string,
        public gitlabLink?:string,
        public nom?:string,
        public email?:string,
        public mdp?:string,
        
    ){}
}